### ISSUE TITLE
Вывод в Excel либо в CSV

### ISSUE THREAD

**Issue by siberianisaev** [siberianisaev/NeutronBarrel#1]
http://xlslib.sourceforge.net
http://www.libxl.com

**Comment by Svirihin** [comment]
Андрюх, вроде бы разобрался, все работает как надо. Четко разделяются две активности, с разными периодами. Очень хорошо. Задача наивысшего приоритета, как появится свободная минутка - прогони пожалуйста через программу ВСЕ данные по 250-нобелию с vasftp2. Причем И через версию для "мам" (где ты ищешь FFront), и версию для "дочек" (где ищешь FdFront). Третья версия с условием или-или оставим до пятницы. В первом приближении данные уже очень интересные.

**Comment by siberianisaev** [comment]
https://www.dropbox.com/s/c7heabqb7xrvrtc/250No_all.zip?dl=0

**Comment by Svirihin** [comment]
Нам с тобой надо будет калибровку рекойлов обсудить. Об остальном завтра поговорим.

**Comment by siberianisaev** [comment]
Использовал CHCSVParser  https://github.com/davedelong/CHCSVParser
**При открытии в Excel разделителем будет запятая**
