### ISSUE TITLE
ветка Migration ошибки

### ISSUE THREAD

**Issue by Svirihin** [siberianisaev/NeutronBarrel#27]
прогоняю данные 2015 года новой версией (Migration) обнаружился ряд непонятностей:

1.  почему то при поиске рекойлов данные (дельта между осколком и рекойлом) выводятся с минусом, оно вроде и не страшно, но непонятно - в других ветках такого нет..
2. в ветке MASTER ошибка с поиском осколков устранена, а здесь я опять вижу удвоенную амплитуду при суммировании энергии FFront
3. поиск Gamma - все таки непонятно, по моему ищет она в одном направлении. Либо при выводе возникает ошибка, например когда я задаю дельту для поиска 30мкс, то она находит все Гаммы со знаком плюс и при этом несколько событий вида: 1,84467E19 (около 20 штук именно таких, одинаковых времен). Выод нужен именно такой - если нашла при поиске вперед - ставим плюс, если нашла при поиске назад - минус.

**Comment by Svirihin** [comment]
было бы неплохо из ветки new_time_2017 в мастер-ветку перенести изменения связанные с маркером (доп. столбцы). По маркерам окончательно: Рекойлы это - 100, 111, 110, 101 (т.е. все события у которых 16й бит НЕ НОЛЬ). В последнем прогоне новых данных, из-за того что за маркер мы считали только события 100 - в осколки записалось просто адское количество неверных событий. При этом, кстати, мы могли потерять некоторое количество правильных рекойлов - ибо например комбинация 101 в случае короткого времени жизни весьма вероятна. А мы ее отбрасываем. Т.е. нужно добавить еще один столбец, где эти самые маркеры писать для рекойлов (а не только для FFront, FBack, FWel). Это можно отработать на ветке new_time_2017 - и потом добавить в master.

**Comment by siberianisaev** [comment]
done
