### ISSUE TITLE
Вынести протокол данных в отдельный файл из кода / либо подгружать его из PRO файлов при чтении данных

### ISSUE THREAD

**Issue by siberianisaev** [siberianisaev/NeutronBarrel#7]

**Comment by Svirihin** [comment]
В программе не так уж много параметров. Осколки, нейтроны, рекойлы, гамма, фон, триггер - их можно прописывать каждый раз перед запуском (ессно, с возможностью сохранить в виде конфиг. файла), т.е. сопоставлять - какому id какое событие соответствует
